// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFjp1VW8l5WYALy0jxyq_7gy6VhPlhseI',
    appId: '1:697004962823:web:6dbf4ef12367f231e3e6a2',
    messagingSenderId: '697004962823',
    projectId: 'mohammed-raqi-app',
    authDomain: 'mohammed-raqi-app.firebaseapp.com',
    storageBucket: 'mohammed-raqi-app.firebasestorage.app',
    measurementId: 'G-S3Z9EPXG9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDERbDDGMday3Jgh18hkZ25wGR2D2dvQCo',
    appId: '1:697004962823:android:b28d4f1771425aa9e3e6a2',
    messagingSenderId: '697004962823',
    projectId: 'mohammed-raqi-app',
    storageBucket: 'mohammed-raqi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOkUrZP04F5JOTPYdHMkDvdNqvSJbMLXA',
    appId: '1:697004962823:ios:7726485cdf1efa64e3e6a2',
    messagingSenderId: '697004962823',
    projectId: 'mohammed-raqi-app',
    storageBucket: 'mohammed-raqi-app.firebasestorage.app',
    iosBundleId: 'com.example.mohammedRaqiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOkUrZP04F5JOTPYdHMkDvdNqvSJbMLXA',
    appId: '1:697004962823:ios:7726485cdf1efa64e3e6a2',
    messagingSenderId: '697004962823',
    projectId: 'mohammed-raqi-app',
    storageBucket: 'mohammed-raqi-app.firebasestorage.app',
    iosBundleId: 'com.example.mohammedRaqiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFjp1VW8l5WYALy0jxyq_7gy6VhPlhseI',
    appId: '1:697004962823:web:c5139e818a36897ae3e6a2',
    messagingSenderId: '697004962823',
    projectId: 'mohammed-raqi-app',
    authDomain: 'mohammed-raqi-app.firebaseapp.com',
    storageBucket: 'mohammed-raqi-app.firebasestorage.app',
    measurementId: 'G-BPEVZ2XQGQ',
  );
}
